In [ ]:
import numpy as np

In [1]:
#Kig på billedet

In [3]:
import numpy as np
def accum(x):
    # x is np.array with the data matrix
    # output is the accumulator matrix
    rows = x.shape[0]
    cols = x.shape[1]
    accum = np.zeros((rows,cols))
    accum[0,:] = x[0,:]
    for r in range(1,rows):
        accum[r,0] = x[r,0] + min([accum[r-1,0],accum[r-1,1]])
        for c in range(1,(cols-1)):
            accum[r,c] = x[r,c] + min([accum[r-1,c-1],accum[r-1,c],accum[r-1,c+1]])
            accum[r,cols-1] = x[r,cols-1] + min([accum[r-1,cols-2],accum[r-1,cols-1]])
    return accum

In [7]:
x = np.array([[208, 71, 244, 202, 173, 180],
     [231, 139, 124, 245, 193,8],
     [32, 244, 204, 167, 189, 71],
     [233, 246, 36, 9, 100, 12],
     [161, 40, 108, 217, 167, 25],
     [25, 248, 234, 238, 44, 210]])
print(accum(x))

[[208.  71. 244. 202. 173. 180.]
 [302. 210. 195. 418. 366. 181.]
 [242. 439. 399. 362. 370. 252.]
 [475. 488. 398. 371. 352. 264.]
 [636. 438. 479. 569. 431. 289.]
 [463. 686. 672. 669. 333. 499.]]
